"""Initial migration

Revision ID: ec0683c58ac7
Revises: 
Create Date: 2026-08-22 16:30:32.134037

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import uuid


# Custom GUID type for migrations
class GUID(sa.String):
    """Platform-agnostic UUID column type."""
    def __init__(self):
        super().__init__(36)


# revision identifiers, used by Alembic.
revision: str = 'ec0683c58ac7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sites',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_sites_name', 'sites', ['name'], unique=False)
    op.create_table('users',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('actuators',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('site_id', GUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('type', sa.Enum('tuya', 'sonoff', 'shelly', 'tasmota', 'gpio', 'mqtt', 'http', name='actuatortype'), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('is_online', sa.Boolean(), nullable=False),
    sa.Column('last_status', sa.Boolean(), nullable=True),
    sa.Column('last_power_w', sa.Float(), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_actuators_is_enabled', 'actuators', ['is_enabled'], unique=False)
    op.create_index('ix_actuators_site_id', 'actuators', ['site_id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('user_id', GUID(), nullable=True),
    sa.Column('site_id', GUID(), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('resource_type', sa.String(length=64), nullable=True),
    sa.Column('resource_id', GUID(), nullable=True),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_logs_action', 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index('ix_audit_logs_site_id', 'audit_logs', ['site_id'], unique=False)
    op.create_index('ix_audit_logs_user_id', 'audit_logs', ['user_id'], unique=False)
    op.create_table('cameras',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('site_id', GUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('type', sa.Enum('rtsp', 'onvif', 'http', 'hls', 'webcam', 'file', name='cameratype'), nullable=False),
    sa.Column('stream_url', sa.String(length=1024), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('width', sa.Integer(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('fps', sa.Float(), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('is_online', sa.Boolean(), nullable=False),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('onvif_profile', sa.String(length=255), nullable=True),
    sa.Column('ptz_enabled', sa.Boolean(), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_cameras_is_enabled', 'cameras', ['is_enabled'], unique=False)
    op.create_index('ix_cameras_site_id', 'cameras', ['site_id'], unique=False)
    op.create_table('detectors',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('site_id', GUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('type', sa.Enum('yolo', 'motion', 'custom', name='detectortype'), nullable=False),
    sa.Column('model_path', sa.String(length=1024), nullable=True),
    sa.Column('model_config', sa.JSON(), nullable=False),
    sa.Column('classes', sa.JSON(), nullable=False),
    sa.Column('color_ranges', sa.JSON(), nullable=False),
    sa.Column('confidence_threshold', sa.Float(), nullable=False),
    sa.Column('iou_threshold', sa.Float(), nullable=False),
    sa.Column('min_detections', sa.Integer(), nullable=False),
    sa.Column('require_frames', sa.Integer(), nullable=False),
    sa.Column('auto_resolve_frames', sa.Integer(), nullable=False),
    sa.Column('update_every', sa.Float(), nullable=False),
    sa.Column('detect_every', sa.Float(), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_detectors_is_enabled', 'detectors', ['is_enabled'], unique=False)
    op.create_index('ix_detectors_site_id', 'detectors', ['site_id'], unique=False)
    op.create_table('invite_tokens',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('created_by', GUID(), nullable=False),
    sa.Column('site_id', GUID(), nullable=True),
    sa.Column('role', sa.Enum('ADMIN', 'OPERATOR', 'VIEWER', name='userrole'), nullable=False),
    sa.Column('max_uses', sa.Integer(), nullable=False),
    sa.Column('used_count', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_invite_tokens_created_by', 'invite_tokens', ['created_by'], unique=False)
    op.create_index(op.f('ix_invite_tokens_token'), 'invite_tokens', ['token'], unique=True)
    op.create_table('notifiers',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('site_id', GUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.Enum('telegram', 'email', 'pushover', 'webhook', 'mqtt', 'signal', name='notifiertype'), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('notify_on_trigger', sa.Boolean(), nullable=False),
    sa.Column('notify_on_ack', sa.Boolean(), nullable=False),
    sa.Column('notify_on_resolve', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_notifiers_is_enabled', 'notifiers', ['is_enabled'], unique=False)
    op.create_index('ix_notifiers_site_id', 'notifiers', ['site_id'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('user_id', GUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_refresh_tokens_expires_at', 'refresh_tokens', ['expires_at'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_token_hash'), 'refresh_tokens', ['token_hash'], unique=False)
    op.create_index('ix_refresh_tokens_user_id', 'refresh_tokens', ['user_id'], unique=False)
    op.create_table('site_users',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('site_id', GUID(), nullable=False),
    sa.Column('user_id', GUID(), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'OPERATOR', 'VIEWER', name='userrole'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('site_id', 'user_id', name='uq_site_user')
    )
    op.create_index('ix_site_users_site_id', 'site_users', ['site_id'], unique=False)
    op.create_index('ix_site_users_user_id', 'site_users', ['user_id'], unique=False)
    op.create_table('system_logs',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('site_id', GUID(), nullable=True),
    sa.Column('level', sa.String(length=16), nullable=False),
    sa.Column('logger', sa.String(length=128), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('context', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_system_logs_created_at'), 'system_logs', ['created_at'], unique=False)
    op.create_index('ix_system_logs_level', 'system_logs', ['level'], unique=False)
    op.create_index('ix_system_logs_site_id', 'system_logs', ['site_id'], unique=False)
    op.create_table('actuator_bindings',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('camera_id', GUID(), nullable=False),
    sa.Column('actuator_id', GUID(), nullable=False),
    sa.Column('detector_id', GUID(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actuator_id'], ['actuators.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['camera_id'], ['cameras.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['detector_id'], ['detectors.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('camera_id', 'actuator_id', name='uq_camera_actuator')
    )
    op.create_index('ix_actuator_bindings_actuator_id', 'actuator_bindings', ['actuator_id'], unique=False)
    op.create_index('ix_actuator_bindings_camera_id', 'actuator_bindings', ['camera_id'], unique=False)
    op.create_table('alarms',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('site_id', GUID(), nullable=False),
    sa.Column('camera_id', GUID(), nullable=False),
    sa.Column('detector_id', GUID(), nullable=False),
    sa.Column('state', sa.Enum('triggered', 'acknowledged', 'resolved', 'silenced', name='alarmstate'), nullable=False),
    sa.Column('trigger_frame_path', sa.String(length=1024), nullable=True),
    sa.Column('trigger_frame_url', sa.String(length=1024), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('detection_class', sa.String(length=128), nullable=True),
    sa.Column('color_fraction', sa.Float(), nullable=True),
    sa.Column('acknowledged_by', GUID(), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('alarm_metadata', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['acknowledged_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['camera_id'], ['cameras.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['detector_id'], ['detectors.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_alarms_camera_id', 'alarms', ['camera_id'], unique=False)
    op.create_index('ix_alarms_created_at', 'alarms', ['created_at'], unique=False)
    op.create_index('ix_alarms_site_id', 'alarms', ['site_id'], unique=False)
    op.create_index('ix_alarms_state', 'alarms', ['state'], unique=False)
    op.create_table('rules',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('site_id', GUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('camera_id', GUID(), nullable=False),
    sa.Column('detector_id', GUID(), nullable=True),
    sa.Column('actuator_id', GUID(), nullable=False),
    sa.Column('action', sa.Enum('on', 'off', 'toggle', name='ruleaction'), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('cooldown_seconds', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actuator_id'], ['actuators.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['camera_id'], ['cameras.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['detector_id'], ['detectors.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_rules_actuator_id', 'rules', ['actuator_id'], unique=False)
    op.create_index('ix_rules_camera_id', 'rules', ['camera_id'], unique=False)
    op.create_index('ix_rules_site_id', 'rules', ['site_id'], unique=False)
    op.create_table('zones',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('camera_id', GUID(), nullable=False),
    sa.Column('rows', sa.Integer(), nullable=False),
    sa.Column('cols', sa.Integer(), nullable=False),
    sa.Column('cell', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['camera_id'], ['cameras.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('camera_id')
    )
    op.create_table('alarm_media',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('alarm_id', GUID(), nullable=False),
    sa.Column('media_type', sa.String(length=32), nullable=False),
    sa.Column('file_path', sa.String(length=1024), nullable=False),
    sa.Column('url', sa.String(length=1024), nullable=True),
    sa.Column('thumbnail_path', sa.String(length=1024), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['alarm_id'], ['alarms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_alarm_media_alarm_id', 'alarm_media', ['alarm_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_alarm_media_alarm_id', table_name='alarm_media')
    op.drop_table('alarm_media')
    op.drop_table('zones')
    op.drop_index('ix_rules_site_id', table_name='rules')
    op.drop_index('ix_rules_camera_id', table_name='rules')
    op.drop_index('ix_rules_actuator_id', table_name='rules')
    op.drop_table('rules')
    op.drop_index('ix_alarms_state', table_name='alarms')
    op.drop_index('ix_alarms_site_id', table_name='alarms')
    op.drop_index('ix_alarms_created_at', table_name='alarms')
    op.drop_index('ix_alarms_camera_id', table_name='alarms')
    op.drop_table('alarms')
    op.drop_index('ix_actuator_bindings_camera_id', table_name='actuator_bindings')
    op.drop_index('ix_actuator_bindings_actuator_id', table_name='actuator_bindings')
    op.drop_table('actuator_bindings')
    op.drop_index('ix_system_logs_site_id', table_name='system_logs')
    op.drop_index('ix_system_logs_level', table_name='system_logs')
    op.drop_index(op.f('ix_system_logs_created_at'), table_name='system_logs')
    op.drop_table('system_logs')
    op.drop_index('ix_site_users_user_id', table_name='site_users')
    op.drop_index('ix_site_users_site_id', table_name='site_users')
    op.drop_table('site_users')
    op.drop_index('ix_refresh_tokens_user_id', table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_token_hash'), table_name='refresh_tokens')
    op.drop_index('ix_refresh_tokens_expires_at', table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index('ix_notifiers_site_id', table_name='notifiers')
    op.drop_index('ix_notifiers_is_enabled', table_name='notifiers')
    op.drop_table('notifiers')
    op.drop_index(op.f('ix_invite_tokens_token'), table_name='invite_tokens')
    op.drop_index('ix_invite_tokens_created_by', table_name='invite_tokens')
    op.drop_table('invite_tokens')
    op.drop_index('ix_detectors_site_id', table_name='detectors')
    op.drop_index('ix_detectors_is_enabled', table_name='detectors')
    op.drop_table('detectors')
    op.drop_index('ix_cameras_site_id', table_name='cameras')
    op.drop_index('ix_cameras_is_enabled', table_name='cameras')
    op.drop_table('cameras')
    op.drop_index('ix_audit_logs_user_id', table_name='audit_logs')
    op.drop_index('ix_audit_logs_site_id', table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index('ix_audit_logs_action', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index('ix_actuators_site_id', table_name='actuators')
    op.drop_index('ix_actuators_is_enabled', table_name='actuators')
    op.drop_table('actuators')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index('ix_sites_name', table_name='sites')
    op.drop_table('sites')
    # ### end Alembic commands ###